---
- name: use apt over https
  apt: 
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common']
    state: present
    
- pip:
    name: docker-py

- name: ensure repository key is installed
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: False

- name: ensure docker registry is available
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu  xenial stable' state=present

- name: ensure docker and dependencies are installed
  apt: 
    name: docker-ce
    state: present 
    update_cache: yes

- service: name=docker state=restarted